### ISSUE TITLE
not enough room to add .rsrc section header

### ISSUE THREAD

**Issue by fabienblin** [tc-hib/go-winres#11] opened 2023-02-02 10:35 UTC
Hello,

I'm trying to compile a program for Windows/amd64 using this module and it works fine to add an icon and manifest with the `go-winres patch` command on a small test version of my app.
I get `not enough room to add .rsrc section header` when doing the same compilation on the definitive version of the same app that is much larger. I dont understand why the header size would be different and i can't find a relatable solution on internet.
I tried adding the `--delete` option but it didn't change anything.

Any idea of the reason I could have this strange behaviour?

Thx

**Comment by fabienblin** [comment] 2023-02-02 13:25
I resolved the problem by removing the patch command from my Makefile and only using go-winres make

**Comment by tc-hib** [comment] 2023-03-14 13:40
Hello,

Would you be able to share the exe file with me?
I'd like to see why this error happened.

Thanks.

**Comment by tc-hib** [comment] 2023-03-14 13:56
I'm closing this issue, as it's probably not a bug.

When using the `patch` command, some cases are impossible to handle.
For example, when the exe file doesn't already contain an rsrc section and there isn't any space left to add one.

You've done the right thing:
When you build an exe file, it's always better to use `make` and let the linker add the rsrc section.
`patch` is there to modify an exe file you can't build yourself.

**Closed by tc-hib** 2023-03-14 13:56 UTC
